### ISSUE TITLE
Skin isn't remembered.

### ISSUE THREAD

**Issue by wziard** [minetest-mods/character_creator#18] opened 2019-01-14 15:17 UTC
On a (reasonably recent) 5.0.0 minetest (server & client) when I log out and log in again, the player has reverted to the default skin. If I start /character_creator again I see that the mod has remembered my settings, but not applied them. As soon as I click one button the correct skin is loaded.

**Comment by bell07** [comment] 2019-01-15 04:53
Tried shortly and cannot reproduce the issue. Maybe do you have any other additional skins-related mods? Which version/fork?

**Comment by wziard** [comment] 2019-01-15 10:54
I found out it's the same issue as https://github.com/minetest-mods/character_creator/issues/17

adding the delay makes it work.

**Comment by bell07** [comment] 2019-01-16 05:14
Can you pls. add some debugging prints to check how the race condition appears? I still cannot see how the issue happens and cannot reproduce them

**Comment by wziard** [comment] 2019-01-16 11:24
I'll look into it. I don't really know about the race condition though, I just noticed that the fix from that issue makes the skins appear correctly on re-login
.

**Comment by wziard** [comment] 2019-01-16 17:39
<ACTION> 2019-01-16 18:37:19: [Server] Test [178.226.99.80] joins game.
<ACTION> 2019-01-16 18:37:19: [Server] Test joins game. List of players: Test
2019-01-16 18:37:19: [Server] load skin start
2019-01-16 18:37:19: [Server] load skin end
2019-01-16 18:37:19: [Server] change skin start
<WARNING> 2019-01-16 18:37:19: [Server] 3d_armor: Detached armor inventory is nil [set_player_armor]
2019-01-16 18:37:19: [Server] change skin end
<WARNING> 2019-01-16 18:37:20: [Server] Assignment to undeclared global "num" inside a function

**Comment by wziard** [comment] 2019-01-16 17:39
I put minetest.log calls at the start and end of load_skin and change_skin
Looks like maybe a race condition with 3d armor?

**Comment by bell07** [comment] 2019-01-16 18:34
Are you with minetest game 5? Maybe it is a additional dependency to the new mod player_api helps.

Does the mod work without 3d_armor?

**Comment by bell07** [comment] 2019-01-16 18:42
From 3d_armor:
```
minetest.register_on_joinplayer(function(player)
	default.player_set_model(player, "3d_armor_character.b3d")
	minetest.after(0, function(player)
		if init_player_armor(player) == false then
			pending_players[player] = 0
		end
	end, player)
end)
```
All register_on_joinplayer are executed in same game-step, but both mods does plan the next task with minetest.after(0,function).
1. 3d_armor => init_player_armor
2. character_creator => change_skin

If the order is right it works as expected. If the order changes (can random happens) you get the issue.
Idea: Please try to replace the line 26

 [armor:set_player_armor(player)](https://github.com/minetest-mods/character_creator/blob/master/init.lua#L216) by
```
minetest.after(0, armor.set_player_armor, armor, player)
```

This should scedule the character_creator's skin update in 3d_armor to the next game step if the 3d_armor is initialized anyway.

**Comment by nonchip** [comment] 2020-08-20 12:41
a year later this is still an issue in my game rn (with 3d armor being applied while complaining its inventory is nil, and the skin getting reset) even though @bell07 seems to have found a literally one-liner solution, is there anything preventing this from just being added to the repo or did people just forget about it? would be nice not to have to fork the mod just for a single line :D

note: when adding skinsdb to my game it did it correctly, i assume because skinsdb doesn't have this issue and gets the skin to set from character creator.

**Comment by bell07** [comment] 2020-08-23 15:11
I think it's just forgotten.. I proposed a fix but did not get any confirmation the issue is fixed by this line. @nonchip, can you confirm the fix does work for character_creator + 3d_armor without skinsdb?
For information: With skinsdb the skinsdb does manage the initialisation for both mods, so the race-condition does not appear

**Comment by nonchip** [comment] 2020-08-23 16:39
> For information: With skinsdb the skinsdb does manage the initialisation for both mods, so the race-condition does not appear

i thought so yeah

> can you confirm the fix does work for character_creator + 3d_armor without skinsdb?

it seems to work for me yeah, temporarily did the change and it didn't happen anymore. but since it's a race condition and i'm not quite sure what 3d_armor is actually trying to do there, i can't be too sure

**Closed as completed** 2020-08-24 06:18 UTC
